1212. Team Scores in Football Tournament
Medium

/*
SQL Schema
Create table If Not Exists Teams (team_id int, team_name varchar(30))
Create table If Not Exists Matches (match_id int, host_team int, guest_team int, host_goals int, guest_goals int)
Truncate table Teams
insert into Teams (team_id, team_name) values ('10', 'Leetcode FC')
insert into Teams (team_id, team_name) values ('20', 'NewYork FC')
insert into Teams (team_id, team_name) values ('30', 'Atlanta FC')
insert into Teams (team_id, team_name) values ('40', 'Chicago FC')
insert into Teams (team_id, team_name) values ('50', 'Toronto FC')
Truncate table Matches
insert into Matches (match_id, host_team, guest_team, host_goals, guest_goals) values ('1', '10', '20', '3', '0')
insert into Matches (match_id, host_team, guest_team, host_goals, guest_goals) values ('2', '30', '10', '2', '2')
insert into Matches (match_id, host_team, guest_team, host_goals, guest_goals) values ('3', '10', '50', '5', '1')
insert into Matches (match_id, host_team, guest_team, host_goals, guest_goals) values ('4', '20', '30', '1', '0')
insert into Matches (match_id, host_team, guest_team, host_goals, guest_goals) values ('5', '50', '30', '1', '0')
*/

Table: Teams

+---------------+----------+
| Column Name   | Type     |
+---------------+----------+
| team_id       | int      |
| team_name     | varchar  |
+---------------+----------+
team_id is the primary key of this table.
Each row of this table represents a single football team.
 

Table: Matches

+---------------+---------+
| Column Name   | Type    |
+---------------+---------+
| match_id      | int     |
| host_team     | int     |
| guest_team    | int     | 
| host_goals    | int     |
| guest_goals   | int     |
+---------------+---------+
match_id is the primary key of this table.
Each row is a record of a finished match between two different teams. 
Teams host_team and guest_team are represented by their IDs in the Teams table (team_id), and they scored host_goals and guest_goals goals, respectively.
 

You would like to compute the scores of all teams after all matches. Points are awarded as follows:
A team receives three points if they win a match (i.e., Scored more goals than the opponent team).
A team receives one point if they draw a match (i.e., Scored the same number of goals as the opponent team).
A team receives no points if they lose a match (i.e., Scored fewer goals than the opponent team).
Write an SQL query that selects the team_id, team_name and num_points of each team in the tournament after all described matches.

Return the result table ordered by num_points in decreasing order. In case of a tie, order the records by team_id in increasing order.

The query result format is in the following example.

 

Example 1:

Input: 
Teams table:
+-----------+--------------+
| team_id   | team_name    |
+-----------+--------------+
| 10        | Leetcode FC  |
| 20        | NewYork FC   |
| 30        | Atlanta FC   |
| 40        | Chicago FC   |
| 50        | Toronto FC   |
+-----------+--------------+
Matches table:
+------------+--------------+---------------+-------------+--------------+
| match_id   | host_team    | guest_team    | host_goals  | guest_goals  |
+------------+--------------+---------------+-------------+--------------+
| 1          | 10           | 20            | 3           | 0            |
| 2          | 30           | 10            | 2           | 2            |
| 3          | 10           | 50            | 5           | 1            |
| 4          | 20           | 30            | 1           | 0            |
| 5          | 50           | 30            | 1           | 0            |
+------------+--------------+---------------+-------------+--------------+
Output: 
+------------+--------------+---------------+
| team_id    | team_name    | num_points    |
+------------+--------------+---------------+
| 10         | Leetcode FC  | 7             |
| 20         | NewYork FC   | 3             |
| 50         | Toronto FC   | 3             |
| 30         | Atlanta FC   | 1             |
| 40         | Chicago FC   | 0             |
+------------+--------------+---------------+

--SOLUTION 
WITH POINTS AS 
(
               SELECT HOST_TEAM AS TEAM_ID,
                    SUM(HOST_POINTS) AS TPOINTS
               FROM (
                         SELECT HOST_TEAM,
                         CASE 
                              WHEN HOST_GOALS > GUEST_GOALS THEN 3
                              WHEN HOST_GOALS = GUEST_GOALS THEN 1
                              ELSE 0
                         END AS HOST_POINTS
                         FROM MATCHES 
               ) AS A
               GROUP BY HOST_TEAM
        UNION ALL
               SELECT 
                    GUEST_TEAM AS TEAM_ID,
                    SUM(GUEST_POINTS) AS TPOINTS
               FROM (     SELECT  
                          GUEST_TEAM,
                          CASE 
                            WHEN GUEST_GOALS > HOST_GOALS THEN 3
                            WHEN GUEST_GOALS = HOST_GOALS THEN 1
                            ELSE 0
                          END AS GUEST_POINTS
                          FROM MATCHES 
                   ) AS B
               GROUP BY GUEST_TEAM 
), SUMMARY AS 
(

     SELECT TEAM_ID, SUM(TPOINTS) AS TPOINTS
     FROM POINTS
     GROUP BY TEAM_ID
)

SELECT 
T.TEAM_ID, 
T.TEAM_NAME, 
CASE 
          WHEN S.TPOINTS IS NULL THEN 0
          ELSE S.TPOINTS 
END AS NUM_POINTS 
FROM TEAMS AS T LEFT JOIN SUMMARY AS S
ON T.TEAM_ID = S.TEAM_ID
ORDER BY NUM_POINTS DESC, TEAM_ID ASC 